version: '3.7'
services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gobarber
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5433:5432'
  db_mongo:
    image: mongo
    volumes:
      - /var/lib/mongodb/data
    ports:
      - '27017:27017'
  redis:
    image: redis:apline
    ports:
      - '6379:6379'
